package proyecto2;


import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.util.Scanner;
import javax.swing.JTextField;
import java.util.ArrayList;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class frmFormasdePago extends javax.swing.JFrame {
 ArrayList arrCodigo;
    ArrayList arrNit;
    ArrayList arrClientes;
    ArrayList arrIdVentas;
    ArrayList arrPagar;
    ArrayList arrTotal;
    ArrayList arrVuelto;
    
    //Arrays para pago con tarjeta        
    ArrayList arrTitular;
    ArrayList arrNumeroTarjeta;
    ArrayList arrNumeroAAA;
    ArrayList arrNumeroCVC;
    ArrayList arrNumeroMM;
    /**
     * Creates new form frmFormasdePago
     */
    public frmFormasdePago() {
             Scanner teclado = new Scanner(System.in);
        initComponents();
        lblIndice.setVisible(false);
        lblIndice.setText("-1");
  
    arrNit = new ArrayList();
    arrClientes = new ArrayList();
    arrIdVentas = new ArrayList();
    arrPagar = new ArrayList();
    arrTotal = new ArrayList();
    arrVuelto = new ArrayList();
    
    //Arrays para pago con tarjeta        
    arrTitular = new ArrayList();
    arrNumeroTarjeta = new ArrayList();
    arrNumeroAAA = new ArrayList();
    arrNumeroCVC = new ArrayList();
    arrNumeroMM = new ArrayList();
   
        this.setLocationRelativeTo(null);
             panelEfectivo.setVisible(false);
             panelTarjeta.setVisible(false);
             panelTransferencia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEfectivo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        panelTarjeta = new javax.swing.JPanel();
        botonLimpiar2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroTarjeta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtmM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtaA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcvc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTitularTarjeta = new javax.swing.JTextField();
        botonAceptar1 = new javax.swing.JButton();
        botonSeleccionar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        radioBoton = new javax.swing.JRadioButton();
        radioBoton2 = new javax.swing.JRadioButton();
        radioBoton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        panelTransferencia = new javax.swing.JPanel();
        botonAceptar2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtNoCuenta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        botonLimpiar3 = new javax.swing.JButton();
        lblIndice = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblCantidadReg = new javax.swing.JLabel();
        panelEfectivo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNit = new javax.swing.JTextField();
        textCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textidVentas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textPagar = new javax.swing.JTextField();
        botonLimpiar1 = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        btnIdVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMAS DE PAGO");

        panelTarjeta.setBorder(javax.swing.BorderFactory.createTitledBorder("Tarjeta de crédito o débito"));

        botonLimpiar2.setText("Limpiar");
        botonLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiar2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Número de la Tarjeta: ");

        txtNumeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTarjetaActionPerformed(evt);
            }
        });

        jLabel8.setText("MM");

        jLabel9.setText("AA");

        jLabel10.setText("/");

        jLabel11.setText("CVC");

        txtcvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcvcActionPerformed(evt);
            }
        });

        jLabel12.setText("Titular de la Tarjeta: ");

        botonAceptar1.setText("Aceptar");
        botonAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTarjetaLayout = new javax.swing.GroupLayout(panelTarjeta);
        panelTarjeta.setLayout(panelTarjetaLayout);
        panelTarjetaLayout.setHorizontalGroup(
            panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitularTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTarjetaLayout.createSequentialGroup()
                        .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonAceptar1)
                            .addGroup(panelTarjetaLayout.createSequentialGroup()
                                .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTarjetaLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel9))
                                    .addGroup(panelTarjetaLayout.createSequentialGroup()
                                        .addComponent(txtmM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtaA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTarjetaLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtcvc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelTarjetaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonLimpiar2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTarjetaLayout.setVerticalGroup(
            panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTarjetaLayout.createSequentialGroup()
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel11))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtmM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(txtcvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTitularTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiar2)
                    .addComponent(botonAceptar1))
                .addContainerGap())
        );

        botonSeleccionar.setText("Seleccionar");
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        grupoEfectivo.add(radioBoton);
        radioBoton.setText("Efectivo");
        radioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBotonActionPerformed(evt);
            }
        });

        grupoEfectivo.add(radioBoton2);
        radioBoton2.setText("Tarjeta de crédito o débito");

        grupoEfectivo.add(radioBoton3);
        radioBoton3.setText("Transferencia bancaria");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panelTransferencia.setBorder(javax.swing.BorderFactory.createTitledBorder("Transferencia Bancaria"));

        botonAceptar2.setText("Aceptar");
        botonAceptar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptar2ActionPerformed(evt);
            }
        });

        jLabel13.setText("No. de Cuenta:");

        jLabel14.setText("Nombre del propietario");

        botonLimpiar3.setText("Limpiar");
        botonLimpiar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransferenciaLayout = new javax.swing.GroupLayout(panelTransferencia);
        panelTransferencia.setLayout(panelTransferenciaLayout);
        panelTransferenciaLayout.setHorizontalGroup(
            panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransferenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar2)
                .addGap(18, 18, 18)
                .addComponent(botonLimpiar3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
            .addGroup(panelTransferenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(30, 30, 30)
                .addGroup(panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNoCuenta)
                    .addComponent(txtPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransferenciaLayout.setVerticalGroup(
            panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransferenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(panelTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar2)
                    .addComponent(botonLimpiar3))
                .addContainerGap())
        );

        lblIndice.setText("0");

        jLabel15.setText("PAGOS HECHOS:");

        lblCantidadReg.setText("0");

        panelEfectivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Efectivo"));
        panelEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelEfectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEfectivoMouseClicked(evt);
            }
        });

        jLabel2.setText("NIT:");

        jLabel3.setText("idCliente:");

        textNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNitActionPerformed(evt);
            }
        });

        jLabel4.setText("IdVentas");

        jLabel5.setText("Total a pagar:");

        textTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTotalActionPerformed(evt);
            }
        });

        jLabel6.setText("Pagado con:");

        botonLimpiar1.setText("Limpiar");
        botonLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiar1ActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        btnIdVenta.setText("Buscar IdVenta");
        btnIdVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEfectivoLayout = new javax.swing.GroupLayout(panelEfectivo);
        panelEfectivo.setLayout(panelEfectivoLayout);
        panelEfectivoLayout.setHorizontalGroup(
            panelEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfectivoLayout.createSequentialGroup()
                .addGroup(panelEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelEfectivoLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(36, 36, 36)
                            .addComponent(textNit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelEfectivoLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(textCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelEfectivoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textidVentas)))
                .addGroup(panelEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelEfectivoLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(panelEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(panelEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textTotal)
                            .addComponent(textPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelEfectivoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEfectivoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnIdVenta)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelEfectivoLayout.setVerticalGroup(
            panelEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfectivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(textPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEfectivoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textidVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIdVenta))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(panelEfectivoLayout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(panelEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonAceptar)
                            .addComponent(botonLimpiar1))))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEfectivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(radioBoton)
                                .addGap(18, 18, 18)
                                .addComponent(radioBoton2)
                                .addGap(18, 18, 18)
                                .addComponent(radioBoton3)
                                .addGap(18, 18, 18)
                                .addComponent(botonSeleccionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lblIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel1)
                                .addGap(121, 121, 121)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(lblCantidadReg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelTarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblIndice))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(lblCantidadReg)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBoton2)
                    .addComponent(radioBoton3)
                    .addComponent(radioBoton)
                    .addComponent(botonSeleccionar)
                    .addComponent(botonLimpiar))
                .addGap(37, 37, 37)
                .addComponent(panelEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiar2ActionPerformed
        // TODO add your handling code here:
        txtTitularTarjeta.setText("");
        txtNumeroTarjeta.setText("");
        txtmM.setText("");
        txtaA.setText("");
        txtcvc.setText("");
    }//GEN-LAST:event_botonLimpiar2ActionPerformed

    private void txtNumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTarjetaActionPerformed

    private void txtcvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcvcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcvcActionPerformed

    private void botonAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptar1ActionPerformed
        // TODO add your handling code here:
        String titular=txtTitularTarjeta.getText();
        String numeroTarjeta=txtNumeroTarjeta.getText();
        String numerocvc=txtcvc.getText();
        String numeroaa=txtaA.getText();
                String idVentas=textidVentas.getText();
        String numeromm=txtmM.getText();
        /*   int numeroTarjeta=Integer.parseInt(txtNumeroTarjeta.getText());
        int numerocvc=Integer.parseInt(txtcvc.getText());
        int numeroaa=Integer.parseInt(txtaA.getText());
        int numeromm=Integer.parseInt(txtmM.getText());
        int cantidad=18;*/
        
arrIdVentas.add(idVentas);
    arrTitular.add(titular);
    arrNumeroTarjeta.add(numeroTarjeta);
    arrNumeroAAA.add(numeroaa);
    arrNumeroCVC.add(numerocvc);
    arrNumeroMM.add(numeromm);    
   lblCantidadReg.setText(Integer.toString(arrIdVentas.size()));
        
   try{
            PreparedStatement stmt = null;
            Connection con = Conectar.getConexion();
            stmt = con.prepareStatement("INSERT INTO pagostarjeta VALUES (?, ?, ?, ?, ?, ?)");
              stmt.setString(1, lblCantidadReg.getText());
            stmt.setString(2, titular);
            stmt.setString(3, numeroTarjeta);
            stmt.setString(4, numeromm);
            stmt.setString(5, numeroaa);
            stmt.setString(6, numerocvc);
         
            
            int retorno = stmt.executeUpdate();
            if (retorno>0)
                JOptionPane.showMessageDialog(null, "Pago agregado");
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
   

    }//GEN-LAST:event_botonAceptar1ActionPerformed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        // TODO add your handling code here:
        if (radioBoton.isSelected()){
            panelEfectivo.setVisible(true);
            panelTarjeta.setVisible(false);
            panelTransferencia.setVisible(false);
        }
        if(radioBoton2.isSelected()){
            panelEfectivo.setVisible(false);
            panelTarjeta.setVisible(true);
            panelTransferencia.setVisible(false);
        }
        if(radioBoton3.isSelected()){
            panelEfectivo.setVisible(false);
            panelTarjeta.setVisible(false);
            panelTransferencia.setVisible(true);
        }
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
        grupoEfectivo.clearSelection();
        panelEfectivo.setVisible(false);
        panelTarjeta.setVisible(false);
        panelTransferencia.setVisible(false);

    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void radioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBotonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
              frmMenu Menu = new frmMenu();
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonAceptar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptar2ActionPerformed
        // TODO add your handling code here:
        txtPropietario.setText("JOSE ALFREDO DE LEON MARTINEZ");
        txtNoCuenta.setText("518788942318455");
        //
    }//GEN-LAST:event_botonAceptar2ActionPerformed

    private void botonLimpiar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiar3ActionPerformed
        // TODO add your handling code here:
        txtNoCuenta.setText("");
        txtPropietario.setText("");
    }//GEN-LAST:event_botonLimpiar3ActionPerformed

    private void textNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNitActionPerformed

    private void textTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTotalActionPerformed

    private void botonLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiar1ActionPerformed
        // TODO add your handling code here:

        textNit.setText("");
        textCliente.setText("");
        textidVentas.setText("");
        textTotal.setText("");
        textPagar.setText("");

    }//GEN-LAST:event_botonLimpiar1ActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:

        String nit=textNit.getText();
        String clientes=textCliente.getText();
        String idVentas=textidVentas.getText();
        int numeroPagar=Integer.parseInt(textPagar.getText());
        String numeroPagar2=textPagar.getText();
        String numeroTotal2=textTotal.getText();
        int numeroTotal=Integer.parseInt(textTotal.getText());
        //String total=textTotal.getText();

        int vueltoTotal= -(numeroTotal-numeroPagar);

        if(numeroPagar>numeroTotal)
        {
            JOptionPane.showMessageDialog(null,"Id de Ventas: " + idVentas + "\nCliente con nombre: " + clientes + "\nNIT: " + nit + "\nCon total a pagar de: " + numeroTotal + "\nTendra un vuelto de: " + vueltoTotal );

            arrNit.add(nit);
            arrClientes.add(clientes);
            arrIdVentas.add(idVentas);
            arrPagar.add(numeroPagar2);
            arrTotal.add(numeroTotal2);
            arrVuelto.add(vueltoTotal);
            lblCantidadReg.setText(Integer.toString(arrIdVentas.size()));
            

             try{
            PreparedStatement stmt = null;
            Connection con = Conectar.getConexion();
            stmt = con.prepareStatement("INSERT INTO pagosefectivo VALUES (?, ?, ?, ?, ?, ?)"); 
            stmt.setString(1, lblCantidadReg.getText());
            stmt.setString(2, nit);          
            stmt.setString(3, clientes);
            stmt.setString(4, idVentas);
            stmt.setString(6, numeroPagar2);
            stmt.setString(5, numeroTotal2);
         
            
            int retorno = stmt.executeUpdate();
            if (retorno>0)
                JOptionPane.showMessageDialog(null, "Pago agregado");
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
            
            textNit.setText("");
            textCliente.setText("");
            textidVentas.setText("");
            textTotal.setText("");
            textPagar.setText("");

        } else if(numeroPagar==numeroTotal)
        {
            JOptionPane.showMessageDialog(null,"Id de Ventas: " + idVentas + "\nCliente con nombre: " + clientes + "\nNIT: " + nit + "\nCon total a pagar de: " + numeroTotal + "\nSu pago fue exitoso." );

            arrNit.add(nit);
            arrClientes.add(clientes);
            arrIdVentas.add(idVentas);
            arrPagar.add(numeroPagar2);
            arrTotal.add(numeroTotal2);
            lblCantidadReg.setText(Integer.toString(arrIdVentas.size()));

                         try{
            PreparedStatement stmt = null;
            Connection con = Conectar.getConexion();
            stmt = con.prepareStatement("INSERT INTO pagosefectivo VALUES (?, ?, ?, ?, ?, ?)"); 
            stmt.setString(1, lblCantidadReg.getText());
            stmt.setString(2, nit);          
            stmt.setString(3, clientes);
            stmt.setString(4, idVentas);
            stmt.setString(6, numeroPagar2);
            stmt.setString(5, numeroTotal2);
         
            
            int retorno = stmt.executeUpdate();
            if (retorno>0)
                JOptionPane.showMessageDialog(null, "Pago agregado");
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
            
            
            textNit.setText("");
            textCliente.setText("");
            textidVentas.setText("");
            textTotal.setText("");
            textPagar.setText("");

        }else
        {
            JOptionPane.showMessageDialog(null,"Id de Ventas: " + idVentas + "\nCliente con nombre: " + clientes + "\nNIT: " + nit + "\nCon total a pagar de: " + numeroTotal + "\nUsted no ha pagado la cantidad exacta" );
        }

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void btnIdVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdVentaActionPerformed
        // TODO add your handling code here:
        int indice = arrIdVentas.indexOf(textidVentas.getText());
        if(indice != -1)
        {

            /* String Pagar = Integer.toString((int) arrPagar.get(indice));
            String Total = Integer.toString((int) arrTotal.get(indice));
            String Nit = Integer.toString((int) arrNit.get(indice));*/

            textNit.setText((String) arrNit.get(indice) );
            textCliente.setText((String) arrClientes.get(indice));
            textidVentas.setText((String) arrIdVentas.get(indice));
            textPagar.setText((String) arrPagar.get(indice));
            textTotal.setText((String) arrTotal.get(indice));

            /* textPagar.setText(Pagar);
            textPagar.setText(Total);
            textNit.setText(Nit);*/

            lblIndice.setText(Integer.toString(indice));

        }else {
            lblIndice.setText("-1");
            JOptionPane.showMessageDialog(rootPane, "Este idVenta no existe...");
        }
    }//GEN-LAST:event_btnIdVentaActionPerformed

    private void panelEfectivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEfectivoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEfectivoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFormasdePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFormasdePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFormasdePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFormasdePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFormasdePago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAceptar1;
    private javax.swing.JButton botonAceptar2;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonLimpiar1;
    private javax.swing.JButton botonLimpiar2;
    private javax.swing.JButton botonLimpiar3;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JButton btnIdVenta;
    private javax.swing.ButtonGroup grupoEfectivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCantidadReg;
    public static javax.swing.JLabel lblIndice;
    private javax.swing.JPanel panelEfectivo;
    private javax.swing.JPanel panelTarjeta;
    private javax.swing.JPanel panelTransferencia;
    private javax.swing.JRadioButton radioBoton;
    private javax.swing.JRadioButton radioBoton2;
    private javax.swing.JRadioButton radioBoton3;
    private javax.swing.JTextField textCliente;
    private javax.swing.JTextField textNit;
    private javax.swing.JTextField textPagar;
    private javax.swing.JTextField textTotal;
    private javax.swing.JTextField textidVentas;
    private javax.swing.JTextField txtNoCuenta;
    private javax.swing.JTextField txtNumeroTarjeta;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtTitularTarjeta;
    private javax.swing.JTextField txtaA;
    private javax.swing.JTextField txtcvc;
    private javax.swing.JTextField txtmM;
    // End of variables declaration//GEN-END:variables
}
