package proyecto2;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class frmProductos extends javax.swing.JFrame {
 ArrayList arrCódigo;
    ArrayList arrNombre;
    ArrayList arrPrecio;
    ArrayList arrStock;
    ArrayList arrProveedor;
    ArrayList arrCod;
    ArrayList arrTipo;
    ArrayList arrCate;
    /**
     * Creates new form frmProductos
     */
    public frmProductos() {
        initComponents();
        lblIndice.setVisible(false);
        txtCate.setVisible(false);
        lblIndice.setText("-1");
        arrCódigo = new ArrayList();
        arrNombre = new ArrayList();
        arrPrecio = new ArrayList();
        arrStock = new ArrayList();
        arrProveedor = new ArrayList();
        arrTipo = new ArrayList();
        arrCod = new ArrayList();
        arrCate = new ArrayList();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Proveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbt_Tipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btn_Buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_Nuevo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_Guardar = new javax.swing.JButton();
        txt_Código = new javax.swing.JTextField();
        btn_Actualizar = new javax.swing.JButton();
        txt_Nombre = new javax.swing.JTextField();
        btn_Eliminar = new javax.swing.JButton();
        txt_Precio = new javax.swing.JTextField();
        btn_Cerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_CantReg = new javax.swing.JLabel();
        txt_Stock = new javax.swing.JTextField();
        lblIndice = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_BuscarIndice = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        txtCate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("idArticulo");

        cbt_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Línea Blanca", "Línea Marrón", "Línea Gris", "PAE" }));
        cbt_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbt_TipoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        btn_Buscar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Precio:");

        btn_Nuevo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_Nuevo.setText("Nuevo");
        btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Stock:");

        btn_Guardar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        txt_Código.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CódigoActionPerformed(evt);
            }
        });

        btn_Actualizar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        btn_Eliminar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btn_Cerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Cerrar.setText("Cerrar");
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("PRODUCTOS");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Productos Registrados:");

        lbl_CantReg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_CantReg.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CantReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CantReg.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_CantReg, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addComponent(lbl_CantReg))
        );

        lblIndice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIndice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndice.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Tipo:");

        btn_BuscarIndice.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_BuscarIndice.setText("Buscar por índice");
        btn_BuscarIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarIndiceActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Proveedor:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("cod_articulo");

        txtCate.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Cerrar)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcod, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(txt_Código)
                    .addComponent(txt_Nombre)
                    .addComponent(txt_Precio)
                    .addComponent(txt_Stock, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(txtCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_Proveedor)
                                .addComponent(cbt_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Nuevo)
                            .addComponent(btn_Guardar)
                            .addComponent(btn_Actualizar)
                            .addComponent(btn_Buscar)
                            .addComponent(btn_BuscarIndice)
                            .addComponent(btn_Eliminar))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_Código, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Nuevo))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_BuscarIndice)
                                .addGap(11, 11, 11)
                                .addComponent(btn_Actualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Eliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txt_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbt_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblIndice)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Cerrar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        boolean existeCódigo = arrCódigo.contains(txt_Código.getText());
        if (existeCódigo) {
            JOptionPane.showMessageDialog(rootPane, "Este Código y Artículo ya existe...");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Este Código y Artículo No existe...");
        }
        lblIndice.setText("-1");
    }//GEN-LAST:event_btn_BuscarActionPerformed
 private void Limpiar(){
        txt_Código.setText(null);
        txt_Nombre.setText(null);
        txt_Precio.setText(null);
        txt_Stock.setText(null);
        txt_Proveedor.setText(null);
        txtcod.setText(null);
        txtCate.setText("0");
        cbt_Tipo.setSelectedIndex(0);
        txt_Código.requestFocus();
    }
    private void btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoActionPerformed
        this.Limpiar();
    }//GEN-LAST:event_btn_NuevoActionPerformed
        
    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed

        String vCódigo = txt_Código.getText();
        String vNombre = txt_Nombre.getText();
        String vPrecio = txt_Precio.getText();
        String vStock = txt_Stock.getText();
        String vCod = txtcod.getText();
        String vProveedor = txt_Proveedor.getText();
        String vTipo = (String) cbt_Tipo.getSelectedItem();
  
         if (vTipo=="Línea Blanca"){                
          txtCate.setText("0");   
          arrCate.add(txtCate.getText());
            }else if(vTipo=="Línea Marrón") {                
                txtCate.setText("1");  
                          arrCate.add(txtCate.getText());
            }else if(vTipo=="Línea Gris") {                
                txtCate.setText("2");  
                          arrCate.add(txtCate.getText());
            }else  {                
                txtCate.setText("3");  
                          arrCate.add(txtCate.getText());
            }
           

        int opcion = JOptionPane.showConfirmDialog(null,"¿Desea grabar este nuevo registro" + "?");
        if (opcion == JOptionPane.NO_OPTION || opcion == JOptionPane.CANCEL_OPTION) {
            return;
        }

        arrCódigo.add(vCódigo);
        arrNombre.add(vNombre);
        arrPrecio.add(vPrecio);
        arrStock.add(vStock);
        arrProveedor.add(vProveedor);
        arrTipo.add(vTipo);
        arrCod.add(vCod);
        lbl_CantReg.setText(Integer.toString(arrCódigo.size()));
                
        try{
            PreparedStatement stmt = null;
            Connection con = Conectar.getConexion();
            stmt = con.prepareStatement("INSERT INTO productos VALUES (?, ?, ?, ?, ?, ?, ?)"); 
            stmt.setString(1, vCódigo);
            stmt.setString(2, vCod);
            stmt.setString(3, vNombre);
            stmt.setString(4, vPrecio);
            stmt.setString(6, vStock);
            stmt.setString(5, vProveedor);
            stmt.setString(7, txtCate.getText());
            
            int retorno = stmt.executeUpdate();
            if (retorno>0)
                JOptionPane.showMessageDialog(null, "Producto agregado");
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }

        this.Limpiar();
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void txt_CódigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CódigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CódigoActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed

                String vCódigo = txt_Código.getText();
        String vNombre = txt_Nombre.getText();
        String vPrecio = txt_Precio.getText();
        String vStock = txt_Stock.getText();
        String vProveedor = txt_Proveedor.getText();
        String vCate = txtCate.getText();
        String vTipo = (String) cbt_Tipo.getSelectedItem();
        
        if (lblIndice.getText().equals("-1")){
            JOptionPane.showMessageDialog(rootPane, "No ha buscado ningun Artículo..");
        }
        
        int esteIndice = Integer.parseInt( lblIndice.getText());
        String esteTipo = (String) cbt_Tipo.getSelectedItem();

        arrCódigo.set(esteIndice, txt_Código.getText());
        arrNombre.set(esteIndice, txt_Nombre.getText());
        arrPrecio.set(esteIndice, txt_Precio.getText());
        arrStock.set(esteIndice, txt_Stock.getText());
        arrProveedor.set(esteIndice, txt_Proveedor.getText());
        arrCate.set(esteIndice, txtCate.getText());
        arrTipo.set(esteIndice, vTipo);
        txtCate.setText(vTipo);
       
                 try{
            PreparedStatement stmt = null;
            Connection con = Conectar.getConexion();
            stmt = con.prepareStatement("UPDATE productos SET Nombre=(?), Referencia=(?), idProveedor=(?), Stock=(?), idCategoría=(?) WHERE cod_producto=(?)");  

             stmt.setString(1, vNombre);
             stmt.setString(2, vPrecio);
             stmt.setString(3, vProveedor);
             stmt.setString(4, vStock);
                          stmt.setString(5, vCate);
            stmt.setString(6, vCódigo);
 
                        
            int retorno = stmt.executeUpdate();
            if (retorno>0)
                JOptionPane.showMessageDialog(null, "Proveedor modificado");
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        if (lblIndice.getText().equals("-1")){
            JOptionPane.showMessageDialog(rootPane, "No ha buscano ningun Producto..");
            return;
        }
        
        
        
        
        int esteIndice = Integer.parseInt( lblIndice.getText());
        
                 String indiceBD = (String) arrCódigo.set(esteIndice, txtcod.getText());
        try
        {
            PreparedStatement stmt = null;
            
            Connection con= Conectar.getConexion();
                stmt = con.prepareStatement("DELETE FROM productos WHERE cod_producto = ?");
             
             stmt.setString(1, indiceBD);
                     
                     stmt.execute();
                     
                     JOptionPane.showMessageDialog(null, "Producto eliminado...");
        }catch (Exception ex)
        {
    JOptionPane.showMessageDialog(null, ex.toString());
        }
        
        arrCódigo.remove(esteIndice);
        arrNombre.remove(esteIndice);
        arrPrecio.remove(esteIndice);
        arrStock.remove(esteIndice);
        arrProveedor.remove(esteIndice);
        arrTipo.remove(esteIndice);
        lblIndice.setText("-1");
        lbl_CantReg.setText(Integer.toString(arrCódigo.size()));
        
   
        
        this.Limpiar();
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
            frmMenu Menu = new frmMenu();
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CerrarActionPerformed

    private void btn_BuscarIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarIndiceActionPerformed
        int indice = arrCódigo.indexOf(txt_Código.getText());
        if (indice != -1) {
            txt_Nombre.setText((String) arrNombre.get(indice));
            txt_Precio.setText((String) arrPrecio.get(indice));
            txt_Stock.setText((String) arrStock.get(indice));
            txt_Proveedor.setText((String) arrProveedor.get(indice));
            txtCate.setText((String) arrCate.get(indice));
            txtcod.setText((String) arrCod.get(indice));

            String contenido = (String) arrTipo.get(indice);
            if (contenido=="Línea Blanca"){
                cbt_Tipo.setSelectedIndex(0);
            }else if(contenido=="Línea Marrón") {                
                txtCate.setText("1");  
                cbt_Tipo.setSelectedIndex(1);
                          arrCate.add(txtCate.getText());
            }else if(contenido=="Línea Gris") {                
                txtCate.setText("2");  
                cbt_Tipo.setSelectedIndex(2);
                          arrCate.add(txtCate.getText());
            }else  {                
                txtCate.setText("3");  
                cbt_Tipo.setSelectedIndex(3);
                          arrCate.add(txtCate.getText());
            }

            lblIndice.setText(Integer.toString(indice));
        }else {
            lblIndice.setText("-1");
            JOptionPane.showMessageDialog(rootPane, "Este Artículo No existe...");
        }
    }//GEN-LAST:event_btn_BuscarIndiceActionPerformed

    private void cbt_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbt_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbt_TipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_BuscarIndice;
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Nuevo;
    private javax.swing.JComboBox<String> cbt_Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblIndice;
    private javax.swing.JLabel lbl_CantReg;
    private javax.swing.JTextField txtCate;
    private javax.swing.JTextField txt_Código;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Precio;
    private javax.swing.JTextField txt_Proveedor;
    private javax.swing.JTextField txt_Stock;
    private javax.swing.JTextField txtcod;
    // End of variables declaration//GEN-END:variables
}
